import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCVEwYoFxLgNF5/OucFSrtrhk5iXVm48mm6I18kaGVLkQAAAJDEaG1MxGht
TAAAAAtzc2gtZWQyNTUxOQAAACCVEwYoFxLgNF5/OucFSrtrhk5iXVm48mm6I18kaGVLkQ
AAAEDwAr7Nmid3PAMD+6eAyFvVKE/G7DTRRHO4qquBGbvHJZUTBigXEuA0Xn865wVKu2uG
TmJdWbjyabojXyRoZUuRAAAABm15LWtleQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
